- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove depencies that are no long required"
  become: yes
  apt:
    autoremove: yes

- name: "install depencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "create directory"
  file: 
    path: ~/web
    state: directory

- name: copy artifact to web directory
  template: 
    src: files/artifact.tar.gz
    dest: ~/web/artifact.tar.gz

- name: uncompress
  become: yes
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web

- name: build and start node
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start